surname = input( 'Input your surname: ' )
firstname = input( 'Input your firstname: ' )
print( 'Your surname is:', surname)
print( 'Your firstname is:', firstname)
print( 'your full name is:', surname, firstname)